version: '3.8'

services:
  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.function == redis

  # API Gateway
  api_gateway:
    image: kristianrpo30/api-gateway-telematics:latest
    ports:
      - "80:80"
    env_file:
      - ./api_gateway/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.function == api-gateway

  # Microservice Multiplication
  microservice_multiplication:
    image: kristianrpo30/microservice-multiplication-telematics:latest
    ports:
      - "50053:50053"
    env_file:
      - ./micro_services/micro_service_multiplication/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.function == microservice-multiplication


  # Microservice Subtraction
  microservice_subtraction:
    image: kristianrpo30/microservice-subtraction-telematics:latest
    ports:
      - "50054:50054"
    env_file:
      - ./micro_services/micro_service_subtraction/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.function == microservice-subtraction

  # Microservice Sum
  microservice_sum:
    image: kristianrpo30/microservice-sum-telematics:latest
    ports:
      - "50052:50052"
    env_file:
      - ./micro_services/micro_service_sum/.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.function == microservice-sum

  # MOM
  mom:
    image: kristianrpo30/mom-telematics:latest
    ports:
      - "50051:50051"
    env_file:
      - ./mom/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.function == mom


# Definir una red overlay (recomendada en Swarm)
networks:
  default:
    driver: overlay
