# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mom.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmom.proto\x12\x03mom\"d\n\x1cSavePendingServiceParameters\x12\x0f\n\x07task_id\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\"Q\n\x1aSavePendingServiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"F\n RetrievePendingServiceParameters\x12\x0f\n\x07task_id\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x01 \x01(\t\"U\n\x1eRetrievePendingServiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\xcc\x01\n\nMOMService\x12X\n\x12SavePendingService\x12!.mom.SavePendingServiceParameters\x1a\x1f.mom.SavePendingServiceResponse\x12\x64\n\x16RetrievePendingService\x12%.mom.RetrievePendingServiceParameters\x1a#.mom.RetrievePendingServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVEPENDINGSERVICEPARAMETERS']._serialized_start=18
  _globals['_SAVEPENDINGSERVICEPARAMETERS']._serialized_end=118
  _globals['_SAVEPENDINGSERVICERESPONSE']._serialized_start=120
  _globals['_SAVEPENDINGSERVICERESPONSE']._serialized_end=201
  _globals['_RETRIEVEPENDINGSERVICEPARAMETERS']._serialized_start=203
  _globals['_RETRIEVEPENDINGSERVICEPARAMETERS']._serialized_end=273
  _globals['_RETRIEVEPENDINGSERVICERESPONSE']._serialized_start=275
  _globals['_RETRIEVEPENDINGSERVICERESPONSE']._serialized_end=360
  _globals['_MOMSERVICE']._serialized_start=363
  _globals['_MOMSERVICE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
